# -*- coding: utf-8 -*-
# BAGIAN 2: Definisi data test case per modul
# Diimport oleh generate_testcase_run.py

# Format tiap baris:
# (page, tc_id, tc_type, scenario, tc_name, pre_cond, steps, data, expected, post_cond)

# ══════════════════════════════════════════════════════════════
# MODUL 1: LOGIN & LOGOUT
# ══════════════════════════════════════════════════════════════
DATA_LOGIN = [
    ("Login","TC_LOGIN_001","Positive","Login berhasil dengan kredensial valid",
     "Pengguna dapat login dengan sukses menggunakan username & password benar",
     "Pengguna sudah terdaftar di sistem dan akun aktif",
     "1. Buka halaman login\n2. Masukkan username & password valid\n3. Klik tombol 'Login'",
     "Username: admin\nPassword: admin123",
     "Sistem mengarahkan ke halaman dashboard sesuai role pengguna",
     "Pengguna masuk ke halaman dashboard"),
    ("Login","TC_LOGIN_002","Negative","Login gagal karena password salah",
     "Sistem menolak login jika password tidak sesuai",
     "Pengguna sudah terdaftar dan akun aktif",
     "1. Buka halaman login\n2. Masukkan username benar & password salah\n3. Klik 'Login'",
     "Username: admin\nPassword: passwordsalah",
     "Tampil pesan error 'Username atau password yang Anda masukkan salah'",
     "Tetap berada di halaman login"),
    ("Login","TC_LOGIN_003","Negative","Login dengan semua kolom dikosongkan",
     "Sistem tidak mengizinkan login tanpa input data",
     "-",
     "1. Buka halaman login\n2. Biarkan semua field kosong\n3. Klik 'Login'",
     "Username: (kosong)\nPassword: (kosong)",
     "Muncul validasi 'Field wajib diisi' pada kedua kolom",
     "Tetap di halaman login"),
    ("Login","TC_LOGIN_004","Negative","Akses halaman dashboard tanpa login",
     "Sistem harus memblokir akses ke halaman yang memerlukan autentikasi",
     "Pengguna belum login / sesi belum dimulai",
     "1. Buka browser baru\n2. Langsung akses URL /admin/dashboard tanpa login",
     "-",
     "Sistem otomatis redirect ke halaman login",
     "Pengguna diarahkan ke halaman login"),
    ("Login","TC_LOGIN_005","Negative","SQL Injection pada kolom username",
     "Sistem memblokir eksekusi injeksi SQL",
     "-",
     "1. Buka halaman login\n2. Masukkan kode SQL di field username\n3. Klik 'Login'",
     "Username: ' OR '1'='1\nPassword: apapun",
     "Sistem menolak input, tidak terjadi login, tidak ada query yang dieksekusi",
     "Tetap di halaman login, sistem aman dari SQL Injection"),
    ("Login","TC_LOGIN_006","Negative","Input XSS pada kolom username",
     "Sistem tidak mengeksekusi script berbahaya",
     "-",
     "1. Masukkan kode script di field username\n2. Klik 'Login'",
     "Username: <script>alert('XSS')</script>\nPassword: 123",
     "Sistem menolak input atau menampilkan pesan error, script tidak dieksekusi",
     "Tetap di halaman login, sistem aman"),
    ("Logout","TC_LOGOUT_001","Positive","Logout berhasil dari aplikasi",
     "Pengguna berhasil keluar dari sistem",
     "Pengguna sudah login ke sistem",
     "1. Login ke aplikasi\n2. Klik tombol 'Logout' di header/navbar\n3. Konfirmasi logout",
     "-",
     "Sesi dihapus, pengguna diarahkan ke halaman login",
     "Pengguna tidak bisa akses dashboard tanpa login ulang"),
    ("Logout","TC_LOGOUT_002","Negative","Akses dashboard setelah logout",
     "Sistem tidak mengizinkan akses setelah logout",
     "Pengguna sudah login lalu logout",
     "1. Login sebagai user\n2. Logout dari sistem\n3. Tekan tombol back browser\n4. Coba akses URL dashboard",
     "-",
     "Sistem redirect otomatis ke halaman login, sesi tidak aktif",
     "Dashboard tidak bisa diakses, redirect ke login"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 2: DASHBOARD
# ══════════════════════════════════════════════════════════════
DATA_DASHBOARD = [
    ("Dashboard","TC_DASH_001","Positive","Tampilan kartu ringkasan data berhasil dimuat",
     "Dashboard menampilkan jumlah data RPJM, Usulan, dan RKP Desa dengan benar",
     "Pengguna sudah login, ada data di database",
     "1. Login ke sistem\n2. Buka halaman Dashboard",
     "-",
     "Kartu ringkasan menampilkan angka jumlah data yang sesuai dengan database",
     "Pengguna berada di halaman Dashboard"),
    ("Dashboard","TC_DASH_002","Positive","Klik kartu ringkasan mengarahkan ke modul terkait",
     "Navigasi dari kartu dashboard berfungsi dengan benar",
     "Pengguna berada di halaman Dashboard",
     "1. Klik kartu 'RPJM Desa'\n2. Cek halaman yang dituju\n3. Kembali ke dashboard\n4. Klik kartu 'Usulan'",
     "-",
     "Klik kartu RPJM Desa → menuju halaman RPJM Desa; Klik kartu Usulan → menuju halaman Usulan",
     "Pengguna diarahkan ke modul yang sesuai"),
    ("Dashboard","TC_DASH_003","Positive","Filter data dashboard berdasarkan tahun aktif",
     "Dashboard hanya menampilkan data sesuai tahun yang dipilih",
     "Pengguna di Dashboard, terdapat data multi-tahun",
     "1. Pilih tahun 2025 di dropdown filter\n2. Cek angka kartu berubah\n3. Ganti ke tahun 2026",
     "Tahun: 2025 / 2026",
     "Angka di kartu berubah sesuai data pada tahun yang dipilih",
     "Data dashboard terfilter sesuai tahun"),
    ("Dashboard","TC_DASH_004","Positive","Dashboard saat data kosong / belum ada data",
     "Dashboard tetap tampil rapi meski belum ada data",
     "Pengguna login, database kosong atau tahun baru dibuat",
     "1. Login ke sistem\n2. Buka dashboard pada tahun yang belum ada datanya",
     "-",
     "Kartu menampilkan angka '0', tidak ada error, tampilan tetap rapi",
     "Dashboard tampil normal dengan nilai 0"),
    ("Dashboard","TC_DASH_005","Positive","Responsivitas tampilan dashboard di layar kecil",
     "Dashboard tampil baik di resolusi mobile/tablet",
     "Pengguna login, membuka browser",
     "1. Buka dashboard di browser\n2. Ubah ukuran jendela browser ke 768px (tablet)\n3. Ubah ke 360px (mobile)",
     "Lebar jendela: 768px dan 360px",
     "Kartu-kartu dashboard menyesuaikan ukuran layar, tidak ada elemen yang terpotong",
     "Tampilan responsif dan proporsional"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 3: PROFIL & PENGATURAN AKUN
# ══════════════════════════════════════════════════════════════
DATA_PROFIL = [
    ("Profil","TC_PROFIL_001","Positive","Edit data profil dengan data valid",
     "Pengguna berhasil memperbarui data profilnya",
     "Pengguna sudah login, membuka halaman Pengaturan/Profil",
     "1. Buka menu Pengaturan\n2. Edit nama lengkap\n3. Klik tombol Simpan",
     "Nama: Fitria Ramadhani (diubah)",
     "Data profil berhasil diperbarui, muncul notifikasi sukses",
     "Data profil terbaru tersimpan di database"),
    ("Profil","TC_PROFIL_002","Positive","Ubah password dengan data valid",
     "Pengguna berhasil mengganti password akun",
     "Pengguna login, berada di halaman Pengaturan",
     "1. Masukkan password lama\n2. Masukkan password baru\n3. Konfirmasi password baru\n4. Klik Simpan",
     "Password lama: admin123\nPassword baru: newpass456\nKonfirmasi: newpass456",
     "Password berhasil diubah, muncul notifikasi sukses",
     "Pengguna perlu login ulang dengan password baru"),
    ("Profil","TC_PROFIL_003","Negative","Ubah password dengan konfirmasi tidak cocok",
     "Sistem menolak perubahan jika konfirmasi password tidak sesuai",
     "Pengguna login, berada di halaman Pengaturan",
     "1. Masukkan password lama\n2. Masukkan password baru\n3. Masukkan konfirmasi password yang berbeda\n4. Klik Simpan",
     "Password baru: newpass456\nKonfirmasi: newpass789",
     "Muncul pesan error 'Konfirmasi password tidak cocok'",
     "Password tidak berubah, tetap di halaman pengaturan"),
    ("Profil","TC_PROFIL_004","Positive","Upload foto profil dengan format JPG/PNG valid",
     "Foto profil berhasil diunggah dan ditampilkan",
     "Pengguna login, berada di halaman Pengaturan",
     "1. Klik tombol upload foto\n2. Pilih file foto berformat JPG\n3. Klik Simpan",
     "File: foto_profil.jpg (ukuran < 2MB)",
     "Foto profil berhasil diupload dan tampil di halaman profil",
     "Avatar profil berubah ke foto baru"),
    ("Profil","TC_PROFIL_005","Negative","Upload foto dengan format file tidak valid",
     "Sistem menolak upload file selain format gambar",
     "Pengguna login, berada di halaman Pengaturan",
     "1. Klik tombol upload foto\n2. Pilih file berformat PDF atau EXE\n3. Klik Simpan",
     "File: dokumen.pdf",
     "Muncul pesan error 'Format file tidak valid, hanya JPG/PNG yang diizinkan'",
     "Foto profil tidak berubah, tetap foto lama"),
    ("Profil","TC_PROFIL_006","Negative","Ubah password tanpa mengisi field password lama",
     "Sistem tidak mengizinkan ganti password tanpa verifikasi password lama",
     "Pengguna login, berada di halaman Pengaturan",
     "1. Kosongkan field password lama\n2. Isi password baru\n3. Klik Simpan",
     "Password lama: (kosong)\nPassword baru: newpass456",
     "Muncul validasi error 'Password lama wajib diisi'",
     "Password tidak berubah"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 4: NOTIFIKASI
# ══════════════════════════════════════════════════════════════
DATA_NOTIFIKASI = [
    ("Notifikasi","TC_NOTIF_001","Positive","Lihat daftar notifikasi masuk",
     "Daftar notifikasi tampil dengan benar",
     "Pengguna login, ada notifikasi baru di sistem",
     "1. Klik ikon lonceng notifikasi di header\n2. Lihat daftar notifikasi",
     "-",
     "Daftar notifikasi tampil lengkap dengan judul dan waktu",
     "Pengguna melihat daftar notifikasi"),
    ("Notifikasi","TC_NOTIF_002","Positive","Tandai satu notifikasi sebagai sudah dibaca",
     "Status notifikasi berubah menjadi sudah dibaca",
     "Ada notifikasi yang belum dibaca",
     "1. Klik pada satu notifikasi yang belum dibaca",
     "-",
     "Notifikasi berubah status menjadi sudah dibaca (indikator hilang/berubah warna)",
     "Jumlah badge notifikasi berkurang 1"),
    ("Notifikasi","TC_NOTIF_003","Positive","Tandai semua notifikasi sebagai sudah dibaca",
     "Semua notifikasi ditandai dibaca sekaligus",
     "Ada beberapa notifikasi belum dibaca",
     "1. Buka panel notifikasi\n2. Klik 'Tandai Semua Dibaca'",
     "-",
     "Semua notifikasi ditandai sudah dibaca, badge notifikasi menjadi 0 atau hilang",
     "Tidak ada notifikasi yang berstatus belum dibaca"),
    ("Notifikasi","TC_NOTIF_004","Positive","Tampilan saat tidak ada notifikasi baru",
     "Sistem menampilkan pesan kosong jika tidak ada notifikasi",
     "Semua notifikasi sudah dibaca atau belum ada notifikasi",
     "1. Klik ikon notifikasi\n2. Cek tampilan panel",
     "-",
     "Panel menampilkan pesan 'Tidak ada notifikasi baru' atau tampilan kosong yang informatif",
     "Panel notifikasi tampil rapi tanpa error"),
    ("Notifikasi","TC_NOTIF_005","Positive","Klik notifikasi mengarahkan ke halaman yang relevan",
     "Link pada notifikasi berfungsi dengan benar",
     "Ada notifikasi masuk terkait modul tertentu",
     "1. Buka panel notifikasi\n2. Klik pada salah satu notifikasi",
     "-",
     "Pengguna diarahkan ke halaman/modul yang berkaitan dengan isi notifikasi",
     "Pengguna berada di halaman yang tepat sesuai konteks notifikasi"),
]

print("Data modul 1-4 (Login, Dashboard, Profil, Notifikasi) terdefinisi.")
