# -*- coding: utf-8 -*-
# BAGIAN 4: Data test case modul Admin (Tahun, Pengguna, Master Data, Monitoring, Pemulihan)

# ══════════════════════════════════════════════════════════════
# MODUL 10: MANAJEMEN TAHUN
# ══════════════════════════════════════════════════════════════
DATA_TAHUN = [
    ("Tahun","TC_THN_001","Positive","Tambah tahun perencanaan baru yang valid",
     "Data tahun berhasil ditambahkan ke sistem",
     "Admin login, berada di halaman Manajemen Tahun",
     "1. Klik 'Tambah Tahun'\n2. Isi tahun dengan angka valid\n3. Klik 'Simpan'",
     "Tahun: 2027",
     "Tahun berhasil ditambahkan, tampil di daftar dengan status nonaktif",
     "Data tahun 2027 muncul di tabel"),
    ("Tahun","TC_THN_002","Negative","Tambah tahun dengan data yang sudah ada (duplikat)",
     "Sistem menolak penambahan tahun yang sudah terdaftar",
     "Admin login, tahun 2026 sudah ada di sistem",
     "1. Klik 'Tambah Tahun'\n2. Isi tahun 2026\n3. Klik 'Simpan'",
     "Tahun: 2026",
     "Muncul pesan error 'Tahun sudah terdaftar di sistem'",
     "Data tidak ditambahkan, daftar tidak berubah"),
    ("Tahun","TC_THN_003","Positive","Ubah status tahun menjadi Aktif",
     "Status tahun berhasil diubah menjadi aktif",
     "Admin login, ada tahun nonaktif di daftar",
     "1. Pilih tahun yang nonaktif\n2. Klik toggle/tombol 'Aktifkan'\n3. Konfirmasi",
     "Tahun: 2027 (status diubah ke Aktif)",
     "Status tahun berubah menjadi Aktif, sistem menggunakan tahun tersebut",
     "Tahun aktif berubah, pengguna lain mendapatkan tahun baru"),
    ("Tahun","TC_THN_004","Positive","Hapus data tahun yang tidak digunakan",
     "Data tahun berhasil dihapus",
     "Admin login, tahun yang akan dihapus tidak memiliki data terkait",
     "1. Pilih data tahun\n2. Klik 'Hapus'\n3. Konfirmasi 'Ya'",
     "-",
     "Data tahun terhapus, tidak tampil di daftar, notifikasi sukses",
     "Daftar tahun tidak memuat tahun yang dihapus"),
    ("Tahun","TC_THN_005","Negative","Tambah tahun dengan input berupa teks/huruf",
     "Sistem menolak input non-numerik pada field tahun",
     "Admin login, berada di form Tambah Tahun",
     "1. Isi field tahun dengan huruf\n2. Klik 'Simpan'",
     "Tahun: Dua Ribu Dua Tujuh",
     "Muncul validasi 'Tahun harus berupa angka 4 digit'",
     "Data tidak tersimpan, tetap di form"),
    ("Tahun","TC_THN_006","Negative","Tambah tahun tanpa mengisi form (field kosong)",
     "Sistem menolak submit jika field tahun kosong",
     "Admin login, berada di form Tambah Tahun",
     "1. Biarkan field tahun kosong\n2. Klik 'Simpan'",
     "Tahun: (kosong)",
     "Muncul validasi 'Tahun wajib diisi'",
     "Data tidak tersimpan"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 11: MANAJEMEN PENGGUNA
# ══════════════════════════════════════════════════════════════
DATA_PENGGUNA = [
    ("Pengguna","TC_USR_001","Positive","Tambah pengguna baru dengan data lengkap",
     "Akun pengguna baru berhasil dibuat",
     "Admin login, berada di halaman Manajemen Pengguna",
     "1. Klik 'Tambah Pengguna'\n2. Isi nama, username, password, role\n3. Klik 'Simpan'",
     "Nama: Budi Santoso\nUsername: budi_op\nRole: Operator Dusun\nPassword: budi1234",
     "Pengguna baru berhasil ditambahkan dan muncul di daftar",
     "Akun budi_op dapat digunakan untuk login"),
    ("Pengguna","TC_USR_002","Negative","Tambah pengguna dengan username yang sudah ada",
     "Sistem menolak username duplikat",
     "Admin login, username 'admin' sudah terdaftar",
     "1. Klik 'Tambah Pengguna'\n2. Isi username 'admin' (sudah ada)\n3. Klik 'Simpan'",
     "Username: admin",
     "Muncul pesan error 'Username sudah digunakan'",
     "Pengguna baru tidak dibuat"),
    ("Pengguna","TC_USR_003","Positive","Edit/Ubah data dan role pengguna",
     "Perubahan data pengguna berhasil disimpan",
     "Data pengguna tersedia, Admin login",
     "1. Pilih pengguna\n2. Klik 'Edit'\n3. Ubah role\n4. Klik 'Simpan'",
     "Role: Operator Desa (diubah dari Operator Dusun)",
     "Data pengguna diperbarui, role baru aktif saat login berikutnya",
     "Perubahan tersimpan dan tampil di daftar"),
    ("Pengguna","TC_USR_004","Positive","Reset/Ubah password pengguna",
     "Password pengguna berhasil direset oleh Admin",
     "Admin login, data pengguna tersedia",
     "1. Pilih pengguna\n2. Klik 'Reset Password' atau 'Edit'\n3. Isi password baru\n4. Simpan",
     "Password baru: resetpass123",
     "Password berhasil diubah, pengguna bisa login dengan password baru",
     "Pengguna menggunakan password baru untuk login"),
    ("Pengguna","TC_USR_005","Positive","Hapus data pengguna dari sistem",
     "Data pengguna berhasil dihapus",
     "Admin login, data pengguna tersedia",
     "1. Pilih pengguna\n2. Klik 'Hapus'\n3. Konfirmasi 'Ya'",
     "-",
     "Akun pengguna terhapus, tidak dapat login, tidak tampil di daftar",
     "Akun tidak tersedia di sistem"),
    ("Pengguna","TC_USR_006","Negative","Tambah pengguna tanpa mengisi role",
     "Sistem menolak penambahan tanpa role yang dipilih",
     "Admin login, berada di form Tambah Pengguna",
     "1. Isi data lengkap kecuali role\n2. Klik 'Simpan'",
     "Role: (tidak dipilih)",
     "Muncul validasi 'Role pengguna wajib dipilih'",
     "Pengguna tidak dibuat, tetap di form"),
]

# ══════════════════════════════════════════════════════════════
# HELPER: Buat data CRUD standar untuk modul master data
# ══════════════════════════════════════════════════════════════
def crud_master(prefix, label, contoh_data, field_wajib="Nama"):
    return [
        (label, f"TC_{prefix}_001","Positive",f"Tambah data {label} baru",
         f"Data {label} berhasil ditambahkan",
         f"Admin login, berada di halaman Master {label}",
         f"1. Klik 'Tambah {label}'\n2. Isi {field_wajib}\n3. Klik 'Simpan'",
         contoh_data,
         f"Data {label} berhasil ditambahkan dan tampil di tabel",
         f"Data {label} muncul di daftar"),
        (label, f"TC_{prefix}_002","Negative",f"Tambah {label} dengan nama duplikat",
         f"Sistem menolak nama {label} yang sudah ada",
         f"Admin login, data {label} sudah ada di sistem",
         f"1. Klik 'Tambah {label}'\n2. Isi {field_wajib} yang sudah ada\n3. Klik 'Simpan'",
         f"{field_wajib}: (nama yang sudah ada)",
         f"Muncul pesan error '{label} sudah terdaftar'",
         "Data tidak ditambahkan"),
        (label, f"TC_{prefix}_003","Positive",f"Edit/Ubah nama {label}",
         f"Perubahan data {label} berhasil disimpan",
         f"Data {label} tersedia, Admin login",
         f"1. Pilih data {label}\n2. Klik 'Edit'\n3. Ubah {field_wajib}\n4. Klik 'Simpan'",
         f"{field_wajib}: (nama diubah)",
         f"Data {label} berhasil diperbarui, notifikasi sukses",
         f"Data {label} di tabel menampilkan nama terbaru"),
        (label, f"TC_{prefix}_004","Positive",f"Hapus data {label} yang tidak digunakan",
         f"Data {label} berhasil dihapus",
         f"Admin login, data {label} tidak digunakan di modul lain",
         f"1. Pilih data {label}\n2. Klik 'Hapus'\n3. Konfirmasi 'Ya'",
         "-",
         f"Data {label} terhapus, tidak tampil di daftar",
         f"Daftar {label} tidak memuat data yang dihapus"),
        (label, f"TC_{prefix}_005","Negative",f"Tambah {label} tanpa mengisi {field_wajib}",
         f"Sistem menolak penyimpanan jika {field_wajib} kosong",
         f"Admin login, berada di form Tambah {label}",
         f"1. Biarkan field {field_wajib} kosong\n2. Klik 'Simpan'",
         f"{field_wajib}: (kosong)",
         f"Muncul validasi '{field_wajib} wajib diisi'",
         "Data tidak tersimpan"),
    ]

DATA_BIDANG       = crud_master("BDG", "Bidang", "Nama Bidang: Pelaksanaan Pembangunan Desa")
DATA_SUMBER_DANA  = crud_master("SDA", "Sumber Dana", "Nama: Dana Desa")
DATA_POLA         = crud_master("POLA","Pola Pelaksanaan","Nama: Swakelola Tipe I")
DATA_DUSUN        = crud_master("DSN", "Dusun", "Nama Dusun: Dusun Krajan")
DATA_RW           = crud_master("RW",  "RW", "No. RW: 001\nDusun: Dusun Krajan", "No. RW")
DATA_RT           = crud_master("RT",  "RT", "No. RT: 001\nRW: RW 001", "No. RT")
DATA_PEGAWAI      = crud_master("PGW", "Pegawai",
                                "Nama: Budi Santoso\nNIP: 198001012005011001\nJabatan: Sekretaris Desa",
                                "Nama Pegawai")

# ══════════════════════════════════════════════════════════════
# MODUL 19: MONITORING SISTEM
# ══════════════════════════════════════════════════════════════
DATA_MONITORING = [
    ("Monitoring","TC_MON_001","Positive","Buka dan tampilkan tabel log aktivitas pengguna",
     "Tabel log berhasil dimuat dan menampilkan data aktivitas",
     "Admin login, pengguna lain telah melakukan login sebelumnya",
     "1. Klik menu 'Monitoring Sistem'\n2. Lihat tabel log",
     "-",
     "Tabel menampilkan daftar log (nama user, waktu, aktivitas) dengan lengkap",
     "Admin dapat membaca riwayat aktivitas pengguna"),
    ("Monitoring","TC_MON_002","Positive","Filter log berdasarkan tanggal tertentu",
     "Tabel log menampilkan hanya data pada rentang tanggal yang dipilih",
     "Admin login, berada di halaman Monitoring",
     "1. Pilih filter tanggal mulai & selesai\n2. Klik 'Filter'",
     "Tanggal: 01-05-2026 s/d 18-05-2026",
     "Tabel hanya memuat data log pada rentang tanggal tersebut",
     "Data terfilter sesuai tanggal yang dipilih"),
    ("Monitoring","TC_MON_003","Positive","Filter log berdasarkan nama/role pengguna",
     "Tabel log hanya menampilkan aktivitas pengguna tertentu",
     "Admin login, ada beberapa pengguna yang sudah login",
     "1. Isi filter nama pengguna\n2. Klik 'Cari'",
     "Nama: Operator Dusun",
     "Tabel memuat hanya log aktivitas Operator Dusun",
     "Filter berjalan sesuai nama/role yang dicari"),
    ("Monitoring","TC_MON_004","Positive","Lihat detail satu log aktivitas",
     "Detail informasi log tampil saat diklik",
     "Admin login, tabel log sudah memuat data",
     "1. Klik pada salah satu baris log\n2. Lihat detail yang tampil",
     "-",
     "Detail log tampil: IP Address, timestamp, modul yang diakses, jenis aksi",
     "Admin mendapatkan informasi rinci aktivitas"),
    ("Monitoring","TC_MON_005","Negative","Filter dengan format tanggal yang tidak valid",
     "Sistem menolak filter dengan format tanggal salah",
     "Admin login, berada di halaman Monitoring",
     "1. Isi filter tanggal dengan format salah\n2. Klik 'Filter'",
     "Tanggal: 35-13-2027",
     "Muncul validasi 'Format tanggal tidak valid'",
     "Tabel tidak ter-refresh, tetap menampilkan data sebelumnya"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 20: PEMULIHAN DATA
# ══════════════════════════════════════════════════════════════
DATA_PEMULIHAN = [
    ("Pemulihan","TC_PMLN_001","Positive","Lihat daftar data yang telah dihapus (soft delete)",
     "Daftar data terhapus tampil dengan benar",
     "Admin login, ada data yang sudah dihapus (soft delete)",
     "1. Klik menu 'Pemulihan'\n2. Lihat daftar data terhapus",
     "-",
     "Daftar data terhapus tampil lengkap dengan info nama, tanggal hapus, dan modul asal",
     "Admin melihat rekap semua data yang pernah dihapus"),
    ("Pemulihan","TC_PMLN_002","Positive","Pulihkan satu data yang telah dihapus",
     "Data berhasil dikembalikan ke kondisi aktif",
     "Admin login, ada data terhapus di daftar pemulihan",
     "1. Pilih data yang ingin dipulihkan\n2. Klik 'Pulihkan'\n3. Konfirmasi 'Ya'",
     "-",
     "Data kembali muncul di modul asalnya, notifikasi sukses tampil",
     "Data tidak lagi muncul di daftar pemulihan"),
    ("Pemulihan","TC_PMLN_003","Positive","Hapus permanen satu data dari daftar pemulihan",
     "Data terhapus secara permanen dari database",
     "Admin login, ada data di daftar pemulihan",
     "1. Pilih data\n2. Klik 'Hapus Permanen'\n3. Konfirmasi 'Ya'",
     "-",
     "Data terhapus permanen, tidak bisa dipulihkan lagi, notifikasi sukses",
     "Data tidak muncul di daftar pemulihan maupun modul asalnya"),
    ("Pemulihan","TC_PMLN_004","Positive","Cari data terhapus menggunakan fitur pencarian",
     "Fitur pencarian menemukan data yang dimaksud",
     "Admin login, ada beberapa data di daftar pemulihan",
     "1. Ketik kata kunci di searchbox\n2. Tekan Enter atau klik 'Cari'",
     "Kata kunci: Jalan Dusun",
     "Daftar pemulihan ter-filter, hanya menampilkan data yang mengandung kata kunci",
     "Pencarian berjalan dan data yang relevan tampil"),
    ("Pemulihan","TC_PMLN_005","Negative","Batal konfirmasi hapus permanen",
     "Data tidak terhapus jika konfirmasi dibatalkan",
     "Admin login, berada di halaman Pemulihan",
     "1. Pilih data\n2. Klik 'Hapus Permanen'\n3. Klik 'Batal' pada dialog konfirmasi",
     "-",
     "Dialog tertutup, data tetap ada di daftar pemulihan",
     "Tidak ada perubahan pada data"),
]

print("Data modul 10-20 (Admin, Master Data, Monitoring, Pemulihan) terdefinisi.")
