# -*- coding: utf-8 -*-
# BAGIAN 3: Data test case modul RPJM, Usulan, RKP, Berita Acara, Verifikasi

# ══════════════════════════════════════════════════════════════
# MODUL 5: RPJM DESA
# ══════════════════════════════════════════════════════════════
DATA_RPJM = [
    ("RPJM Desa","TC_RPJM_001","Positive","Tambah data RPJM Desa dengan data lengkap",
     "Data RPJM berhasil disimpan ke sistem",
     "Operator Desa sudah login, berada di halaman RPJM Desa",
     "1. Klik tombol 'Tambah RPJM'\n2. Isi semua field form secara lengkap\n3. Klik 'Simpan'",
     "Bidang: Pelaksanaan Pembangunan Desa\nKegiatan: Pembangunan Jalan\nLokasi: Dusun A\nVolume: 100m\nAnggaran: Rp50.000.000",
     "Data RPJM berhasil disimpan, tampil notifikasi sukses, data muncul di tabel",
     "Data RPJM tampil di halaman daftar RPJM"),
    ("RPJM Desa","TC_RPJM_002","Negative","Tambah RPJM tanpa mengisi field wajib (Kegiatan)",
     "Sistem menolak penyimpanan jika field wajib kosong",
     "Operator Desa login, berada di form Tambah RPJM",
     "1. Buka form Tambah RPJM\n2. Kosongkan field 'Nama Kegiatan'\n3. Isi field lainnya\n4. Klik 'Simpan'",
     "Nama Kegiatan: (kosong)",
     "Muncul pesan validasi 'Nama Kegiatan wajib diisi'",
     "Tetap di halaman form, data tidak tersimpan"),
    ("RPJM Desa","TC_RPJM_003","Positive","Edit/Ubah data RPJM Desa yang sudah ada",
     "Perubahan data RPJM berhasil disimpan",
     "Data RPJM sudah tersedia di sistem",
     "1. Pilih data RPJM\n2. Klik tombol 'Edit'\n3. Ubah data volume\n4. Klik 'Simpan'",
     "Volume: 150m (diubah dari 100m)",
     "Data RPJM berhasil diperbarui, notifikasi sukses tampil",
     "Data RPJM di tabel menampilkan data terbaru"),
    ("RPJM Desa","TC_RPJM_004","Positive","Hapus data RPJM Desa (konfirmasi Ya)",
     "Data RPJM berhasil dihapus dari daftar",
     "Data RPJM tersedia, Operator Desa login",
     "1. Pilih data RPJM\n2. Klik tombol 'Hapus'\n3. Pada dialog konfirmasi, klik 'Ya'",
     "-",
     "Data RPJM dihapus (soft delete), tidak tampil di daftar, muncul notifikasi sukses",
     "Daftar RPJM tidak memuat data yang dihapus"),
    ("RPJM Desa","TC_RPJM_005","Negative","Hapus RPJM (konfirmasi Tidak/Batal)",
     "Data tidak terhapus jika pengguna membatalkan konfirmasi",
     "Data RPJM tersedia, Operator Desa login",
     "1. Pilih data RPJM\n2. Klik tombol 'Hapus'\n3. Pada dialog konfirmasi, klik 'Batal'",
     "-",
     "Dialog tertutup, data RPJM tetap ada di daftar",
     "Tidak ada perubahan pada data"),
    ("RPJM Desa","TC_RPJM_006","Positive","Cetak/Export data RPJM Desa ke PDF",
     "Dokumen PDF RPJM berhasil digenerate dan dapat diunduh",
     "Data RPJM tersedia, pengguna berada di halaman RPJM",
     "1. Klik tombol 'Cetak' atau 'Export PDF'\n2. Tunggu proses generate\n3. File ter-download",
     "-",
     "File PDF RPJM berhasil diunduh dengan format tabel yang rapi dan data yang sesuai",
     "File PDF tersimpan di perangkat pengguna"),
    ("RPJM Desa","TC_RPJM_007","Negative","Tambah RPJM dengan input anggaran berupa teks huruf",
     "Sistem menolak input non-numerik pada field anggaran",
     "Operator Desa login, berada di form Tambah RPJM",
     "1. Isi field 'Anggaran' dengan teks huruf\n2. Klik 'Simpan'",
     "Anggaran: Lima Puluh Juta",
     "Muncul pesan validasi 'Anggaran harus berupa angka'",
     "Tetap di form, data tidak tersimpan"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 6: USULAN
# ══════════════════════════════════════════════════════════════
DATA_USULAN = [
    ("Usulan","TC_USLN_001","Positive","Tambah data usulan kegiatan dengan data lengkap",
     "Data usulan berhasil tersimpan di sistem",
     "Operator Dusun sudah login, berada di halaman Usulan",
     "1. Klik 'Tambah Usulan'\n2. Isi semua field form\n3. Klik 'Simpan'",
     "Bidang: Pendidikan\nKegiatan: Pengadaan Meja Kursi\nLokasi: Dusun B\nVolume: 20 set\nAnggaran: Rp10.000.000",
     "Usulan berhasil disimpan, notifikasi sukses tampil, data muncul di tabel",
     "Data usulan tersimpan dan tampil di daftar"),
    ("Usulan","TC_USLN_002","Negative","Tambah usulan tanpa mengisi field wajib (Lokasi)",
     "Sistem menolak penyimpanan jika field wajib kosong",
     "Operator Dusun login, berada di form Tambah Usulan",
     "1. Buka form Tambah Usulan\n2. Kosongkan field 'Lokasi'\n3. Isi field lainnya\n4. Klik 'Simpan'",
     "Lokasi: (kosong)",
     "Muncul pesan validasi 'Lokasi wajib diisi'",
     "Tetap di form, data tidak tersimpan"),
    ("Usulan","TC_USLN_003","Positive","Edit/Ubah data usulan yang sudah ada",
     "Perubahan data usulan berhasil disimpan",
     "Data usulan tersedia, Operator Dusun login",
     "1. Pilih data usulan\n2. Klik tombol 'Edit'\n3. Ubah volume\n4. Klik 'Simpan'",
     "Volume: 25 set (diubah dari 20)",
     "Data usulan berhasil diperbarui, notifikasi sukses tampil",
     "Data usulan di tabel menampilkan data terbaru"),
    ("Usulan","TC_USLN_004","Positive","Hapus data usulan (konfirmasi Ya)",
     "Data usulan berhasil dihapus dari daftar",
     "Data usulan tersedia, Operator Dusun login",
     "1. Pilih data usulan\n2. Klik 'Hapus'\n3. Konfirmasi 'Ya'",
     "-",
     "Data usulan terhapus, notifikasi sukses tampil",
     "Data usulan tidak tampil di daftar"),
    ("Usulan","TC_USLN_005","Positive","Checklist usulan layak untuk masuk RKP Desa",
     "Usulan berhasil ditandai layak dan masuk ke proses RKP",
     "Operator Desa login, data usulan tersedia",
     "1. Buka daftar usulan\n2. Centang/checklist usulan yang layak\n3. Klik 'Simpan Checklist'",
     "-",
     "Status usulan berubah menjadi 'Dipilih/Layak untuk RKP', muncul notifikasi sukses",
     "Usulan masuk ke antrian proses RKP Desa"),
    ("Usulan","TC_USLN_006","Negative","Hapus usulan (konfirmasi Batal/Tidak)",
     "Data tidak terhapus jika pengguna membatalkan",
     "Data usulan tersedia, Operator Dusun login",
     "1. Pilih data usulan\n2. Klik 'Hapus'\n3. Konfirmasi 'Batal'",
     "-",
     "Dialog tertutup, data usulan tetap ada",
     "Tidak ada perubahan pada data"),
    ("Usulan","TC_USLN_007","Negative","Input volume usulan menggunakan huruf",
     "Sistem menolak input non-numerik pada field volume",
     "Operator Dusun login, berada di form Tambah Usulan",
     "1. Isi field 'Volume' dengan huruf\n2. Klik 'Simpan'",
     "Volume: Dua Puluh",
     "Muncul validasi error 'Volume harus berupa angka'",
     "Tetap di form, data tidak tersimpan"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 7: RKP DESA
# ══════════════════════════════════════════════════════════════
DATA_RKP = [
    ("RKP Desa","TC_RKP_001","Positive","Input data RKP Desa dari hasil verifikasi usulan",
     "Data RKP Desa berhasil diinput dari usulan yang sudah diverifikasi",
     "Penyusun RKP login, usulan sudah diverifikasi Layak",
     "1. Buka menu RKP Desa\n2. Pilih usulan yang sudah diverifikasi\n3. Input data RKP\n4. Klik Simpan",
     "Usulan: Pembangunan Jalan\nSumber Dana: Dana Desa\nTahun: 2026",
     "Data RKP Desa berhasil disimpan dan tampil di daftar RKP",
     "RKP Desa tampil dengan status Draft"),
    ("RKP Desa","TC_RKP_002","Negative","Input RKP tanpa mengisi sumber dana",
     "Sistem menolak penyimpanan RKP tanpa sumber dana",
     "Penyusun RKP login, berada di form Input RKP",
     "1. Buka form Input RKP\n2. Kosongkan field 'Sumber Dana'\n3. Klik Simpan",
     "Sumber Dana: (kosong)",
     "Muncul validasi 'Sumber Dana wajib dipilih'",
     "Tetap di form, RKP tidak tersimpan"),
    ("RKP Desa","TC_RKP_003","Positive","Edit/Ubah data RKP Desa",
     "Perubahan data RKP berhasil disimpan",
     "Data RKP tersedia dengan status Draft, Penyusun RKP login",
     "1. Pilih data RKP\n2. Klik 'Edit'\n3. Ubah keterangan/sasaran\n4. Klik Simpan",
     "Sasaran: Masyarakat Dusun A (diubah)",
     "Data RKP berhasil diperbarui dengan notifikasi sukses",
     "Data RKP di tabel menampilkan perubahan terbaru"),
    ("RKP Desa","TC_RKP_004","Positive","Hapus data RKP Desa dengan konfirmasi",
     "Data RKP berhasil dihapus",
     "Data RKP tersedia, Penyusun RKP login",
     "1. Pilih data RKP\n2. Klik 'Hapus'\n3. Konfirmasi 'Ya'",
     "-",
     "Data RKP terhapus dari daftar, notifikasi sukses tampil",
     "Daftar RKP tidak memuat data yang dihapus"),
    ("RKP Desa","TC_RKP_005","Positive","Cetak/Export dokumen RKP Desa ke PDF",
     "Dokumen PDF RKP Desa berhasil digenerate",
     "Data RKP tersedia, pengguna berada di halaman RKP",
     "1. Klik tombol 'Cetak' atau 'Export PDF'\n2. Tunggu generate\n3. File ter-download",
     "-",
     "File PDF RKP Desa diunduh dengan format rapi sesuai standar perencanaan desa",
     "File PDF tersimpan di perangkat"),
    ("RKP Desa","TC_RKP_006","Positive","Approval RKP Desa oleh BPD",
     "RKP Desa disetujui dan status berubah menjadi Final",
     "BPD login, RKP sudah disusun oleh Penyusun RKP",
     "1. Login sebagai BPD\n2. Buka halaman RKP Desa\n3. Klik 'Setujui' (Approve)\n4. Konfirmasi",
     "-",
     "Status RKP berubah menjadi 'Disetujui/Final', muncul notifikasi sukses",
     "RKP Desa berstatus Final dan tidak dapat diedit kembali"),
    ("RKP Desa","TC_RKP_007","Negative","BPD menolak RKP tanpa mengisi alasan penolakan",
     "Sistem menolak aksi penolakan tanpa alasan",
     "BPD login, RKP sudah disusun",
     "1. Buka halaman RKP\n2. Klik 'Tolak/Revisi'\n3. Kosongkan field alasan\n4. Klik Submit",
     "Alasan: (kosong)",
     "Muncul validasi 'Alasan penolakan wajib diisi'",
     "Status RKP tidak berubah, tetap menunggu keputusan BPD"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 8: BERITA ACARA
# ══════════════════════════════════════════════════════════════
DATA_BA = [
    ("Berita Acara","TC_BA_001","Positive","Lihat daftar dan detail Berita Acara",
     "Daftar berita acara tampil dengan benar",
     "Pengguna login, data berita acara tersedia",
     "1. Klik menu 'Berita Acara'\n2. Lihat daftar yang tampil\n3. Klik salah satu untuk melihat detail",
     "-",
     "Daftar BA tampil, klik detail membuka informasi lengkap Berita Acara",
     "Pengguna dapat membaca isi/detail Berita Acara"),
    ("Berita Acara","TC_BA_002","Positive","Unggah dokumen Berita Acara format PDF",
     "File PDF berhasil diunggah ke sistem",
     "Pengguna (Operator Desa/Dusun) login, berada di form unggah BA",
     "1. Klik tombol 'Unggah Berita Acara'\n2. Pilih file PDF\n3. Klik 'Simpan'",
     "File: berita_acara.pdf (ukuran < 5MB)",
     "File berhasil diunggah, tampil di daftar dengan link yang bisa diakses",
     "Dokumen BA tersimpan dan dapat diakses pengguna lain"),
    ("Berita Acara","TC_BA_003","Negative","Unggah dokumen dengan format file tidak valid",
     "Sistem menolak file selain PDF",
     "Pengguna login, berada di form unggah BA",
     "1. Klik tombol 'Unggah Berita Acara'\n2. Pilih file berformat JPG\n3. Klik 'Simpan'",
     "File: gambar_ba.jpg",
     "Muncul pesan error 'Format file tidak valid, hanya PDF yang diizinkan'",
     "File tidak terunggah, tetap di form"),
    ("Berita Acara","TC_BA_004","Positive","Cetak Berita Acara dari sistem",
     "Dokumen Berita Acara berhasil dicetak/diunduh",
     "Data BA tersedia, pengguna berada di halaman BA",
     "1. Pilih data Berita Acara\n2. Klik tombol 'Cetak'\n3. Cek hasil cetak/PDF",
     "-",
     "Halaman cetak terbuka dengan format resmi BA yang rapi (kop surat, data musyawarah)",
     "Dokumen BA berhasil dicetak"),
    ("Berita Acara","TC_BA_005","Positive","Download dokumen Berita Acara yang sudah diunggah",
     "File BA berhasil diunduh ke perangkat pengguna",
     "File BA sudah diunggah, pengguna di halaman daftar BA",
     "1. Pilih data BA\n2. Klik tombol 'Download'\n3. Cek file tersimpan",
     "-",
     "File BA berhasil diunduh ke komputer pengguna",
     "File tersimpan di folder download perangkat"),
    ("Berita Acara","TC_BA_006","Negative","Simpan unggah BA tanpa memilih file",
     "Sistem menolak submit form jika tidak ada file yang dipilih",
     "Pengguna login, berada di form unggah BA",
     "1. Buka form unggah BA\n2. Jangan pilih file apapun\n3. Klik 'Simpan'",
     "File: (tidak dipilih)",
     "Muncul validasi 'File Berita Acara wajib diunggah'",
     "Tetap di form, tidak ada file yang tersimpan"),
]

# ══════════════════════════════════════════════════════════════
# MODUL 9: VERIFIKASI
# ══════════════════════════════════════════════════════════════
DATA_VERIF = [
    ("Verifikasi","TC_VRF_001","Positive","Input hasil verifikasi status Layak",
     "Hasil verifikasi Layak berhasil disimpan",
     "Tim Verifikasi login, data usulan tersedia",
     "1. Buka menu Verifikasi\n2. Pilih data usulan\n3. Pilih status 'Layak'\n4. Klik Simpan",
     "Status: Layak",
     "Hasil verifikasi tersimpan, status usulan berubah menjadi 'Terverifikasi - Layak'",
     "Usulan siap masuk ke tahap penyusunan RKP Desa"),
    ("Verifikasi","TC_VRF_002","Positive","Input verifikasi status Tidak Layak dengan catatan",
     "Hasil verifikasi Tidak Layak beserta alasan berhasil disimpan",
     "Tim Verifikasi login, data usulan tersedia",
     "1. Pilih usulan\n2. Pilih status 'Tidak Layak'\n3. Isi catatan alasan\n4. Klik Simpan",
     "Status: Tidak Layak\nCatatan: Anggaran melebihi pagu yang tersedia",
     "Hasil verifikasi tersimpan dengan catatan, status usulan berubah 'Tidak Layak'",
     "Usulan ditolak dan tidak masuk ke RKP Desa"),
    ("Verifikasi","TC_VRF_003","Negative","Input verifikasi Tidak Layak tanpa catatan/alasan",
     "Sistem menolak penyimpanan jika alasan penolakan tidak diisi",
     "Tim Verifikasi login, data usulan tersedia",
     "1. Pilih usulan\n2. Pilih status 'Tidak Layak'\n3. Kosongkan field catatan\n4. Klik Simpan",
     "Status: Tidak Layak\nCatatan: (kosong)",
     "Muncul validasi 'Catatan/alasan tidak layak wajib diisi'",
     "Data verifikasi tidak tersimpan"),
    ("Verifikasi","TC_VRF_004","Positive","Edit/Ubah hasil verifikasi",
     "Perubahan hasil verifikasi berhasil disimpan",
     "Hasil verifikasi sudah tersedia",
     "1. Buka hasil verifikasi\n2. Klik 'Edit'\n3. Ubah status dari Layak ke Tidak Layak\n4. Isi alasan\n5. Simpan",
     "Status baru: Tidak Layak\nAlasan: Data tidak sesuai dokumen",
     "Hasil verifikasi berhasil diperbarui",
     "Status verifikasi di sistem mencerminkan perubahan terbaru"),
    ("Verifikasi","TC_VRF_005","Positive","Lihat daftar seluruh hasil verifikasi",
     "Tabel hasil verifikasi memuat semua data dengan benar",
     "Tim Verifikasi/Operator Desa/Penyusun RKP login",
     "1. Buka menu Verifikasi\n2. Lihat tabel daftar hasil verifikasi",
     "-",
     "Seluruh data verifikasi tampil di tabel lengkap dengan kolom status",
     "Pengguna dapat membaca rekap hasil verifikasi"),
    ("Verifikasi","TC_VRF_006","Negative","Submit form verifikasi tanpa memilih status",
     "Sistem menolak jika status Layak/Tidak Layak tidak dipilih",
     "Tim Verifikasi login, berada di form verifikasi",
     "1. Buka form verifikasi\n2. Jangan pilih status apapun\n3. Klik Simpan",
     "Status: (tidak dipilih)",
     "Muncul validasi 'Status verifikasi wajib dipilih'",
     "Data tidak tersimpan, tetap di form"),
]

print("Data modul 5-9 (RPJM, Usulan, RKP, BA, Verifikasi) terdefinisi.")
